### ISSUE TITLE
Implement json_server version of the mr_api

### ISSUE THREAD

**Issue by miha42-github** [mediumroast/mr_sdk#3]
# Introduction
Create a high level API and a lower level API driver model that when the API object is created the right API implementation is imported.  This is needed for the purposes of having an operable development environment before the backend is completed.

# Tasks
- [x] Look for examples like in pdfminder.six which has a high-level construct
- [x] Implement the high-level API
- [x] Implement a json-server API driver
- [x] Focus of implementation initially is to create appropriate modifications to interactions and studies; however, reading of companies will also be required.
- [x] Modify companies according to the detail below
- [x] Modify studies according to the detail below 
- [x] Modify interactions objects as needed according to the detail below

# Modifications needed to objects
Since there are cases where it is possible for there to be many `Company` objects without any `Study` objects we need to account for both that scenario.  This results in the ability to compute KeyThemes both for `Study` and `Company` objects which could be interesting.  However, `Study` objects will also have incremental `Questionnaires` that relate to each set of documents and reliably encode the noise in a corpus.  Speaking of corpuses, the intention is to call each collection of interaction an `iteration`.  This matches previous processes that have been enjoyed at companies like Hitachi.  Essentially, a study would start with a set of questions and a first round of interviews.  The results would be incrementally analyzed, producing both a separate questionnaire or modification to the original questionnaire and the next round of interactions.  The sum total of the study would then be analyzed including both iterations with a final report and guidance rendered.   

## Changes for both Studies and Companies
The following data needs to be added in replacement of or in addition to the existing `linkedInteractions` property in both objects.  There are some additional properties that should be talked about include the new counters that count total number of iterations for the entire object and total number of interactions for the entire object.  Additionally, each iteration has an interaction count as well as a state type which in some cases governed by the "sum" of the states for the individual interactions.  State definitions and how the system should move between them follow

### Global Iterations and Iteration instance level
This includes all iterations with consistency between company and study objects.  While the extraction of key themes is well understood for studies, doing something similar for companies is a new topic and unlikely to exist as a feature in early releases.  The intention would be to look at how a company's KeyTheme's have evolved over time.  We can imagine many affordances that are possible for the user such as judging how quickly a "trend" emerges as an individual company over time or even when KeyThemes are detected across a population of companies.  We are essentially preparing the way for future features here with some amount of plumbing.  

1. unthemed_unsummarized - Neither theming or summarization have been processed
2. processing_processing - Both theming and summarization are being processed
3. themed_summarized - both steps are completed (**initially** cannot be achieve by a company, but only by a study)
4. themed_processing - Theming has completed and summarization is in process
5. themed_unsummarized- Theming has finished summarization has not started (**initially** cannot be achieved by company)
6. processing_summarized - Theming is being worked and summarization has completed
7. unthemed_summarized - Theming has not started and summarization has completed (**initially** highest level of a company's iteration status)

### Interactions level
While not mocked up here a state property also needs to be added to each interaction.  All interactions start with an unsummarized state.

1. unsummarized - Summarization hasn't started
2. processing - Summarization is in process
3. summarized - Summarization has completed

```
{
    "studyName | companyName": "foo",
    "iterations": {
       "state": "unprocessed_unprocessed | processing_processing | themed_summarized | themed_processing | processing_summarized | unprocessed_summarized | themed_unprocessed | processing_unprocessed | unprocessed_processing"
        "totalIterations": n,
        "totalInteractions": n,
        "default": {
            "totalInteractions": n,
            "state": "unprocessed_unprocessed | processing_processing | themed_summarized | themed_processing | processing_summarized | unprocessed_summarized | themed_unprocessed | processing_unprocessed | unprocessed_processing"
            "interactions": {
                "interaction_name": {
                      "id": "guid", 
                      "state": "unsummarized | processing | summarized"
                      ...
                },
               ...
                "interaction_name": {
                      "id": "guid", 
                      "state": "unsummarized | processing | summarized"
                      ...
                },
        },
        "1": {
            "totalInteractions": n,
            "state": "unprocessed_unprocessed | processing_processing | themed_summarized | themed_processing | processing_summarized | unprocessed_summarized | themed_unprocessed | processing_unprocessed | unprocessed_processing"
            "interactions": {
                "interaction_name": {
                      "id": "guid", 
                      "state": "unsummarized | processing | summarized"
                },
               ...
                "interaction_name": {
                      "id": "guid", 
                      "status": "unsummarized | processing | summarized"
                },
        },
    },
    ...
}
```

## Changes for Studies
The following data needs to be added in replacement of or in addition to the existing `keyQuestions` property in `Study` objects.  Of note are the additions of new counters for total number of iterations, total number of questions globally for the study and then total number of questions per iteration.  Finally, there is a boolean true/false for inheritance of default questions for each iteration.  While there could be additional complications like multiple levels of inheritance at this early stage we do not know if this is needed and therefor will avoid it.

```
{
    "studyName": "foo"
    "keyQuestions": {
       "totalIterations": n,
       "totalQuestions": n, 
        "default": {
           "totalQuestions": n,
            "1": {
                "question": "Is this a question?",
                "notes": "A free form field with various notes about the question.",
                "included": true | false
            },
            ...
            "n": {
                "question": "Is this a question?",
                "notes": "A free form field with various notes about the question.",
                "included": true | false
            },
        },
        "1": {
            "inheritDefault": true | false,
            "totalQuestions": n,
            "1": {
                "question": "Is this a question?",
                "notes": "A free form field with various notes about the question.",
                "included": true | false
            },
            ...
            "n": {
                "question": "Is this a question?",
                "notes": "A free form field with various notes about the question.",
                "included": true | false
            },
            ...
        "n": {
            "inheritDefault": true | false,
            "totalQuestions": n,
            "1": {
                "question": "Is this a question?",
                "notes": "A free form field with various notes about the question.",
                "included": true | false
            },
            ...
            "n": {
                "question": "Is this a question?",
                "notes": "A free form field with various notes about the question.",
                "included": true | false
            }
        },
     }
}
```
